image: Visual Studio 2017

platform:
    - x64

environment:
    FLEXDLL_RELEASE_FOLDER: "C:/projects/_flexdll_release"
    NPM_TOKEN:
        secure: h3hweU1D+fx2hyHtCSUHVkR7pKf7XpCEwC0/E/a+7vxnus3hArWb4w0WjynzOPJ+

cache:
  - C:/Users/appveyor/.esy/source-tarballs
  - C:/Users/appveyor/.esy/3_/i

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g esy@0.3.4
    # Retry is necessary due to esy/esy#413 and esy/esy#414
    - appveyor-retry esy install

build_script:
    - esy build
    - node esy/create-release.js

deploy_script:
  - ps: |
      if ($ENV:PLATFORM -eq "x64")
      {
        cd $ENV:FLEXDLL_RELEASE_FOLDER
        pwd
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:FLEXDLL_RELEASE_FOLDER ".npmrc") -Encoding UTF8
        iex "npm publish ."
      }
    on:
      branches: master

test: off
