image: Visual Studio 2017

platform:
    - x64

environment:
    FLEXDLL_RELEASE_FOLDER: "C:/Users/appveyor/_flexdll_release"

cache:
  - C:/Users/appveyor/.esy/source-tarballs
  - C:/Users/appveyor/.esy/3_/i
  - C:/users/appveyor/AppData/Roaming/npm

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g esy@0.3.4
    # Retry is necessary due to esy/esy#413 and esy/esy#414
    - appveyor-retry esy install

build_script:
    - esy build
    - node esy/create-release.js
    - cd %FLEXDLL_RELEASE_FOLDER% && npm pack

artifacts:
    - path: C:/Users/appveyor/_flexdll_release
      name: test zip
      type: zip

test: off
